title:             Ashish Agrawal
email:             ashish.agrawal2123@gmail.com
description:       A Hacker with some hunger for innovation :)
author:            Ashish Agrawal
#baseurl:           "/startbootstrap-clean-blog-jekyll"
baseurl:           ""
#url:               "http://blackrockdigital.github.io"
url:               "http://ashish230897.github.io"

# Social Profiles
twitter_username:  AshishSunilAgr1
github_username:   ashish230897
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
